# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=256)),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('entradas_vendidas', models.IntegerField()),
                ('num_consultas', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.CharField(max_length=50)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
